#ifndef __S2_NOW_PLAYING_COMBINER__ISERVER_IDOCV_DSW__V1_0_H__
#define __S2_NOW_PLAYING_COMBINER__ISERVER_IDOCV_DSW__V1_0_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_OFFLINE_DIG_INPUT 0
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_LOCAL_MODE_DIG_INPUT 1
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_UNSUPPORTED_IPOD_DIG_INPUT 2
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_NOT_DOCKED_DIG_INPUT 3
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_ITUNES_MODE_DIG_INPUT 4
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_READING_DATABASE_DIG_INPUT 5
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_FAILED_DATABASE_READ_DIG_INPUT 6
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_DOCKED_DIG_INPUT 7
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_REFRESH_DIG_INPUT 8


/*
* ANALOG_INPUT
*/
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_LOADING_DATABASE_PERCENT_ANALOG_INPUT 0

#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_LINE1$_STRING_INPUT 1
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_LINE1$_STRING_MAX_LEN 255
CREATE_STRING_STRUCT( S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0, __LINE1$, __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_LINE1$_STRING_MAX_LEN );
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_LINE2$_STRING_INPUT 2
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_LINE2$_STRING_MAX_LEN 255
CREATE_STRING_STRUCT( S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0, __LINE2$, __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_LINE2$_STRING_MAX_LEN );
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_TRANSPORT$_STRING_INPUT 3
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_TRANSPORT$_STRING_MAX_LEN 1
CREATE_STRING_STRUCT( S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0, __TRANSPORT$, __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_TRANSPORT$_STRING_MAX_LEN );



/*
* DIGITAL_OUTPUT
*/


/*
* ANALOG_OUTPUT
*/

#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_NOWPLAYING$_STRING_OUTPUT 0
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_NOWPLAYINGLINE1$_STRING_OUTPUT 1
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_NOWPLAYINGLINE2$_STRING_OUTPUT 2
#define __S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0_NOWPLAYINGTRANSPORT$_STRING_OUTPUT 3


/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_STRING_STRUCT( S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0, __LINE1$ );
   DECLARE_STRING_STRUCT( S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0, __LINE2$ );
   DECLARE_STRING_STRUCT( S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0, __TRANSPORT$ );
};

START_NVRAM_VAR_STRUCT( S2_Now_Playing_Combiner__ISERVER_IDOCV_DSW__v1_0 )
{
};



#endif //__S2_NOW_PLAYING_COMBINER__ISERVER_IDOCV_DSW__V1_0_H__

